version: "1.0.0"
services:
  nanr:
    container_name: nanr
    image: nanr
    ports:
      - "4011:4011"
    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"